### PR TITLE
Macos compile errors and warnings

### PR DESCRIPTION
**Pull request by JamesEggleton**
### Description
Cmake build on macOS 10.14.6 failed with:
> Undefined symbols for architecture x86_64:
>   "_AbsoluteToNanoseconds", referenced from:
>       occa::sys::currentTime() in sys.cpp.o
> ld: symbol(s) not found for architecture x86_64

This has been resolved by using mach_timebase_info_data_t instead.

A number of warnings were also emitted relating to C++11 extensions, e.g.
> occa/include/occa/core/device.hpp:249:21: warning: default template arguments for a function template are a C++11 extension
>       [-Wc++11-extensions]
>     template <class TM = void>

These have been silenced using pragmas.

Two deprecated functions, AbsoluteToNanoseconds and syscall, have been factored out:
> occa/src/tools/sys.cpp:68:31: warning: 'AbsoluteToNanoseconds' is deprecated: first deprecated in macOS 10.8
>       [-Wdeprecated-declarations]
>       const Nanoseconds ct2 = AbsoluteToNanoseconds(*(AbsoluteTime *) &ct);
>                               ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/DriverServices.h:93:1: note: 
>       'AbsoluteToNanoseconds' has been explicitly marked deprecated here
> AbsoluteToNanoseconds(AbsoluteTime absoluteTime)              __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
> ^
> occa/src/tools/sys.cpp:369:14: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported;
>       please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
>       return syscall(SYS_gettid);
>              ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/unistd.h:742:6: note: 'syscall' has been
>       explicitly marked deprecated here
> int      syscall(int, ...);

### CODE REVIEW

File: include/occa/core/base.hpp [hunk 1]
```diff
@@ -65,6 +65,9 @@ namespace occa {
                       const void *src = NULL,
                       const occa::properties &props = occa::properties());
 
+#pragma clang diagnostic push
```
Comment (dmed256) [inline include/occa/core/base.hpp:68]: Oh, maybe we're missing the proper C++11 flags when compiling the files
```
-std=c++11 -stdlib=libc++
```

File: src/tools/sys.cpp [hunk 2]
```diff
@@ -366,7 +367,14 @@ namespace occa {
 
     int getTID() {
 #if (OCCA_OS & (OCCA_LINUX_OS | OCCA_MACOS_OS))
-      return syscall(SYS_gettid);
+      #if OCCA_OS == OCCA_MACOS_OS & (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12)
```
Comment (dmed256) [inline src/tools/sys.cpp:370]: 🔥 awesome, thanks for filing + fixing this warning!

**Comment by JamesEggleton** [comment]
I've removed the pragmas, and instead used target_compile_features and target_compile_options to customise warning reporting.

**Comment by dmed256** [comment]
Looks good, thank you for making the changes so fast!
